{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "workload.configMapName" . }}
  labels:
    {{- include "workload.labels" . | nindent 4 }}
    app: {{ include "workload.appLabel" . }}
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: |
{{ tpl $value $ | indent 4 }}
  {{- end }}
{{- end }}
