{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "workload.configMapName" . }}
  labels:
    {{- include "workload.labels" . | nindent 4 }}
data:
  {{- if not (empty .Values.configMap.data) }}
  {{- toYaml .Values.configMap.data | nindent 2 }}
  {{- else }}
  {} # keep valid yaml when enabled but empty
  {{- end }}
{{- end }}
