{{- if .Values.hpa.enabled }}
apiVersion: {{ default "autoscaling/v2" .Values.hpa.apiVersion }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "workload.fullname" . }}
  labels:
    {{- include "workload.labels" . | nindent 4 }}
    app: {{ include "workload.appLabel" . }}
  {{- with .Values.hpa.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ include "workload.workloadKind" . }}
    name: {{ include "workload.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  {{- if .Values.hpa.metrics }}
  metrics:
{{ tpl (toYaml .Values.hpa.metrics) . | indent 4 }}
  {{- end }}
  {{- with .Values.hpa.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
