{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.volumeName }}
  {{- with .Values.persistence.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  persistentVolumeReclaimPolicy: {{ default "Delete" .Values.persistence.persistentVolume.reclaimPolicy }}
  capacity:
    storage: {{ .Values.persistence.persistentVolume.capacity }}
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  {{- with .Values.persistence.persistentVolume.hostPath }}
  hostPath:
    path: {{ . | quote }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.claimName }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.persistentVolumeClaim.requests.storage }}
{{- end }}
