{{- if and .Values.secrets.enabled .Values.secrets.stringData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "workload.secretName" . }}
  labels:
    {{- include "workload.labels" . | nindent 4 }}
    app: {{ include "workload.appLabel" . }}
{{- with .Values.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
type: {{ default "Opaque" .Values.secrets.type }}
stringData:
  {{- range $key, $value := .Values.secrets.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
