{{- if and .Values.istio.enabled (or .Values.istio.hosts .Values.istio.routes) }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "workload.serviceName" . }}
  labels:
    {{- include "workload.labels" . | nindent 4 }}
    app: {{ include "workload.appLabel" . }}
spec:
  {{- if .Values.istio.hosts }}
  hosts:
    {{- toYaml .Values.istio.hosts | nindent 4 }}
  {{- else }}
  hosts:
    - {{ include "workload.serviceName" . }}
  {{- end }}
  {{- with .Values.istio.gateways }}
  gateways:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  http:
  {{- if .Values.istio.routes }}
{{ tpl (toYaml .Values.istio.routes) . | indent 4 }}
  {{- else }}
    - match:
        - uri:
            prefix: {{ default "/" .Values.istio.contextPrefix }}
          headers:
            version:
              exact: pilot
      route:
        - destination:
            host: {{ include "workload.serviceName" . }}
            subset: pilot
            port:
              number: {{ .Values.istio.port }}
    - match:
        - uri:
            prefix: {{ default "/" .Values.istio.contextPrefix }}
      route:
        - destination:
            host: {{ include "workload.serviceName" . }}
            subset: live
            port:
              number: {{ .Values.istio.port }}
  {{- end }}
{{- end }}
