{{- if and .Values.serviceMesh .Values.serviceMesh.istio.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "mesh.baseName" . }}
spec:
  hosts:
    - {{ .Values.serviceMesh.istio.host | quote }}
  gateways:
    - {{ .Values.serviceMesh.istio.gateway | quote }}
  http:
    - name: split-v1-v2
      match:
        - uri:
            prefix: {{ .Values.pathPrefix | default "/" | quote }}
      route:
{{- $root := . }}
{{- range $v := .Values.versionList }}
        - destination:
            host: {{ include "mesh.backendName" (merge (deepCopy $root) (dict "version" $v)) }}
            port:
              {{- include "mesh.portSelector" $root | nindent 14 }}
          weight: {{ index $root.Values.weights $v | default 0 }}
{{- end }}
{{- end }}
