{{- if and .Values.serviceMesh .Values.serviceMesh.istio.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "mesh.baseName" . }}
spec:
  hosts:
    - {{ .Values.serviceMesh.istio.host | quote }}
  gateways:
    - {{ .Values.serviceMesh.istio.gateway | quote }}
  http:
    - name: {{ (index .Values.versionList 0) | default "v1" }}
      match:
        - uri:
            prefix: {{ .Values.pathPrefix | default "/" | quote }}
      route:
        - destination:
            host: {{ include "mesh.backendName" (merge (deepCopy $) (dict "version" ((index .Values.versionList 0) | default "v1"))) }}
            port:
              {{- include "mesh.portSelector" . | nindent 14 }}
          weight: 100
{{- end }}