{{- if and .Values.serviceMesh .Values.serviceMesh.istio.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "mesh.baseName" . }}
spec:
  hosts:
    - {{ .Values.serviceMesh.istio.host | quote }}
  gateways:
    - {{ .Values.serviceMesh.istio.gateway | quote }}
  http:
{{- $root := . }}
{{- $prefix := .Values.routing.prefix | default "/" -}}
{{- if and .Values.routing .Values.routing.canary .Values.routing.canary.enabled }}
    - name: canary-by-header
      match:
        - headers:
            {{ $root.Values.routing.canary.header.name }}:
{{- if eq $root.Values.routing.canary.header.match "exact" }}
              exact: {{ $root.Values.routing.canary.header.value | quote }}
{{- else if eq $root.Values.routing.canary.header.match "prefix" }}
              prefix: {{ $root.Values.routing.canary.header.value | quote }}
{{- else if eq $root.Values.routing.canary.header.match "regex" }}
              regex: {{ $root.Values.routing.canary.header.value | quote }}
{{- else }}
              exact: {{ $root.Values.routing.canary.header.value | quote }}
{{- end }}
        - uri:
            prefix: {{ $prefix | quote }}
      route:
        - destination:
            host: {{ include "mesh.backendName" (merge (deepCopy $root) (dict "version" $root.Values.routing.canary.toVersion)) }}
            port:
              {{- include "mesh.portSelector" $root | nindent 14 }}
          weight: 100
{{- end }}

    - name: split-by-weights
      match:
        - uri:
            prefix: {{ $prefix | quote }}
      route:
{{- range $v := .Values.versionList }}
        - destination:
            host: {{ include "mesh.backendName" (merge (deepCopy $root) (dict "version" $v)) }}
            port:
              {{- include "mesh.portSelector" $root | nindent 14 }}
          weight: {{ index $root.Values.routing.weights $v | default 0 }}
{{- end }}
{{- end }}