
---
kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: <APP_LABEL>
spec:
  host: <APP_LABEL>
  subsets:
    - labels:
        version: live
      name: live
    - labels:
        version: pilot
      name: pilot
---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: <APP_LABEL>
spec:
  hosts:
    - "uat-asmbpmapi.seauat.com.vn" 
  gateways:
    - asm-gateway/bpm-ingress # gateway name
  http:
    - match:
      - uri: # IF matching prefix AND headers version: pilot
          prefix: /<CONTEXT_PREFIX>
        headers:  # AND
          version:
            exact: pilot
      route: # THEN
      - destination:
          port:
            number: 8081
          host: <APP_LABEL> # K8s service as a host subset, enquivalent base service name
          subset: pilot
    - match:
      - uri: # IF
          prefix: /<CONTEXT_PREFIX>
      route:
      - destination:
          port:
            number: 8081
          host: <APP_LABEL> # K8s service as a host subset, enquivalent base service name
          subset: live 