apiVersion: apps/v1
kind: Deployment
metadata:
  name: <APP_NAME>
spec:
  template:
    spec:
      containers:
      - name: <APP_LABEL>
        resources:
          requests:
            memory: 2G
            cpu: 2
          limits:
            memory: 4G
            cpu: 4
---
apiVersion: v1
kind: Service
metadata:
  name: <APP_LABEL>
spec:
  type: NodePort
  selector:
    app: <APP_LABEL>
  ports:
  - name: http-sbapi 
    port: 8081
    targetPort: 8081
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: <APP_NAME> # enquivalent StatefulSet name
spec:
  minReplicas: 1
  maxReplicas: 1 #