{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "workload.secretName" . }}
  labels:
    {{- include "workload.labels" . | nindent 4 }}
type: Opaque
{{- if .Values.secrets.autoMount }}
automountServiceAccountToken: true
{{- end }}
stringData:
  {{- if not (empty .Values.secrets.stringData) }}
  {{- toYaml .Values.secrets.stringData | nindent 2 }}
  {{- else }}
  {} # keep valid yaml when enabled but empty
  {{- end }}
{{- end }}
