{{- /*
templates/workload.yaml
- Render Deployment | StatefulSet tuỳ .Values.workload.kind
- Selector chỉ dùng `app` (ổn định)
- Pod Template gắn checksum/config & checksum/secret để auto-rollout khi ConfigMap/Secret đổi
- Với StatefulSet, spec.serviceName dùng headless (nếu bật) qua helper workload.statefulServiceName
*/ -}}
{{- $kind := include "workload.workloadKind" . -}}

{{- /* Guard cấu hình xấu: STS mà tắt cả service chính & headless */ -}}
{{- if and (eq $kind "StatefulSet") (not (default true .Values.service.headlessEnabled)) (not (default true .Values.service.enabled)) -}}
{{- fail "Invalid config: StatefulSet requires either service.headlessEnabled=true or service.enabled=true to provide spec.serviceName." -}}
{{- end -}}

apiVersion: apps/v1
kind: {{ $kind }}
metadata:
  name: {{ include "workload.fullname" . }}
  labels:
    {{- include "workload.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.workload.replicas }}

  {{- if eq $kind "Deployment" }}
  strategy:
    {{- toYaml .Values.workload.strategy | nindent 4 }}
  {{- else }}
  serviceName: {{ include "workload.statefulServiceName" . }}
  updateStrategy:
    {{- toYaml .Values.workload.strategy | nindent 4 }}
  {{- end }}

  selector:
    matchLabels:
      {{- include "workload.matchLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "workload.selectorLabels" . | nindent 8 }}
        {{- include "workload.labels" . | nindent 8 }}
      annotations:
        {{- $cm := include "workload.configChecksum" . -}}
        {{- $sc := include "workload.secretChecksum" . -}}
        {{- if $cm }}checksum/config: {{ $cm }}{{- end }}
        {{- if $sc }}checksum/secret: {{ $sc }}{{- end }}
        {{- with .Values.workload.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.workload.terminationGracePeriodSeconds }}
      serviceAccountName: {{ include "workload.serviceAccountNameSafe" . }}
      automountServiceAccountToken: {{ include "workload.serviceAccountAutomount" . }}

      {{- with .Values.workload.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}

      {{- with .Values.workload.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.workload.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.workload.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.workload.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.workload.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.workload.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.workload.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.workload.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- /* ===== InitContainers ===== */}}
      {{- with .Values.workload.initContainers }}
      initContainers:
        {{- range . }}
        - name: {{ .name | default "init" | quote }}
          image: "{{ required "initContainers[].image.repository is required" .image.repository }}:{{ required "initContainers[].image.tag is required" .image.tag }}"
          imagePullPolicy: {{ default "IfNotPresent" .image.pullPolicy }}
          {{- with .command }}command: {{ toYaml . | nindent 10 }}{{- end }}
          {{- with .args    }}args:    {{ toYaml . | nindent 10 }}{{- end }}
          {{- with .env     }}env:     {{ toYaml . | nindent 10 }}{{- end }}
          {{- with .envFrom }}envFrom: {{ toYaml . | nindent 10 }}{{- end }}
          {{- with .resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- end }}

      containers:
        # ===== Main container =====
        - name: {{ include "workload.name" . }}
          image: "{{ include "workload.image.repository" . }}/{{ include "workload.image.name" . }}:{{ include "workload.image.tag" . }}"
          imagePullPolicy: {{ include "workload.image.pullPolicy" . }}

          {{- with .Values.workload.main.command }}command: {{ toYaml . | nindent 10 }}{{- end }}
          {{- with .Values.workload.main.args    }}args:    {{ toYaml . | nindent 10 }}{{- end }}

          {{- with .Values.workload.main.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.workload.main.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.workload.main.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.workload.main.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.workload.main.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.workload.main.startupProbe }}
          {{- if or .enabled (hasKey . "httpGet") (hasKey . "exec") (hasKey . "tcpSocket") }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}

          {{- with .Values.workload.main.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.workload.main.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.workload.main.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}

        {{- /* ===== Sidecars ===== */}}
        {{- range .Values.workload.sidecars }}
        - name: {{ .name | required "sidecars[].name is required" }}
          image: "{{ required "sidecars[].image.repository is required" .image.repository }}:{{ required "sidecars[].image.tag is required" .image.tag }}"
          imagePullPolicy: {{ default "IfNotPresent" .image.pullPolicy }}
          {{- with .command }}command: {{ toYaml . | nindent 10 }}{{- end }}
          {{- with .args    }}args:    {{ toYaml . | nindent 10 }}{{- end }}
          {{- with .ports   }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .env     }}env:     {{ toYaml . | nindent 12 }}{{- end }}
          {{- with .envFrom }}envFrom: {{ toYaml . | nindent 12 }}{{- end }}
          {{- with .resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .startupProbe }}
          {{- if or .enabled (hasKey . "httpGet") (hasKey . "exec") (hasKey . "tcpSocket") }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- with .securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}

      {{- with .Values.workload.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
