# =========================
# IDENT / LABEL INPUTS
# =========================
org: []       # optional sb | ptf | asean
env: []       # optional live | pilot | uat
site: []      # optional when State
system: []    # optional

mainLabel: example-workload
# nameOverride: ""        # không dùng -> để helpers tự tính theo mainLabel
fullnameOverride: ""      # để trống -> helpers tự build org-site-env-system-mainLabel

# =========================
# WORKLOAD MAIN
# =========================
workload:
  kind: Deployment
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxSurge: 25%, maxUnavailable: 0 }

  terminationGracePeriodSeconds: 30

  extraPodLabels: {}
  podAnnotations: {}

  nodeSelector: {}
  tolerations: []
  affinity: {}
  topologySpreadConstraints: []

  podSecurityContext:
    runAsNonRoot: true
    fsGroup: 2000
  priorityClassName: ""
  dnsConfig: {}
  hostAliases: []

  volumes:
    - name: cfg
      configMap: { name: "", optional: true }
    - name: tmp
      emptyDir: {}

  imagePullSecrets: []   # [{ name: nexus-repo-secret }]

  main:
    image:
      repository: nexus-img.seabank.com.vn
      # name: ""          # để trống -> mặc định = mainLabel
      tag: "1.0.0"
      pullPolicy: IfNotPresent
    command: []
    args: []
    env:
      - { name: TZ, value: Asia/Ho_Chi_Minh }
      - { name: SPRING_PROFILES_INCLUDE, value: fwbase }
    envFrom: []
    ports:
      - { name: http, containerPort: 8081, protocol: TCP }
    resources:
      requests: { cpu: "1", memory: 1Gi }
      limits:   { cpu: "2", memory: 2Gi }
    volumeMounts:
      - { name: cfg, mountPath: /opt/config }
      - { name: tmp, mountPath: /tmp }
    # livenessProbe: {}
    # readinessProbe: {}
    # startupProbe: {}
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      capabilities: { drop: ["ALL"] }

  initContainers: []
  sidecars: []

service:
  enabled: true           # có thể tắt nếu không cần Service chính
  headlessEnabled: true   # chỉ dùng cho StatefulSet; Deployment sẽ bỏ qua
  headlessName: ""        # để trống -> auto fullname-headless
  name: ""                # để trống -> mặc định fullname
  type: ClusterIP
  annotations: {}
  ports:
    - { name: http, port: 8081, targetPort: 8081 }

configMap:
  enabled: true
  name: ""
  data: {}

secrets:
  enabled: true
  name: ""
  autoMount: true       # tự động add envFrom Secret vào main container
  stringData: {}

serviceAccount:
  create: true
  name: ""
  annotations: {}
  automount: true

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  metrics: []
  behavior: {}

pdb:
  enabled: true
  minAvailable: 1

persistence:
  enabled: false
  volumeName: ""
  claimName: ""
  storageClassName: ""
  accessModes: []
  labels: {}
  persistentVolume:
    reclaimPolicy: Delete
    capacity: 5Gi
    hostPath: ""
  persistentVolumeClaim:
    requests:
      storage: 5Gi
