{{- $cmEnv := .Values.configMap.env | default dict -}}
{{- if and $cmEnv.enabled $cmEnv.data }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "workload.cmEnvName" . }}
  labels:
{{ include "workload.commonLabels" . | nindent 4 }}
data:
{{ toYaml $cmEnv.data | nindent 2 }}
{{- end }}

---

{{- $cmFile := .Values.configMap.file | default dict -}}
{{- if and $cmFile.enabled $cmFile.data }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "workload.cmFileName" . }}
  labels:
{{ include "workload.commonLabels" . | nindent 4 }}
data:
{{ toYaml $cmFile.data | nindent 2 }}
{{- end }}
