{{- if .Values.hpa.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "workload.fullname" . }}
  labels:
    {{- include "workload.commonLabels" . | nindent 4 }}
  {{- with .Values.hpa.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.workload.kind | default "Deployment" }}
    name: {{ include "workload.fullname" . }}
  minReplicas: {{ required "hpa.minReplicas is required" .Values.hpa.minReplicas }}
  maxReplicas: {{ required "hpa.maxReplicas is required" .Values.hpa.maxReplicas }}
  {{- with .Values.hpa.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.hpa.metrics }}
  metrics:
    {{- toYaml . | nindent 4 }}
  {{- else }}
  # Ví dụ mặc định CPU Utilization 80% nếu không truyền metrics
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  {{- end }}
{{- end }}
