{{- if and .Values.pvc.enabled (not .Values.pvc.claimName) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    {{- include "chart.annotations" . | nindent 4 }}
  {{- with .Values.pvc.labels }}
  {{- if .|len }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.pvc.accessModes | nindent 4 }}
  storageClassName: {{ .Values.pvc.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.pvc.persistentVolumeClaim.requests.storage | quote }}
{{- end }}
