{{- if .Values.pvc.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ default (printf "%s-pvc" (include "workload.fullname" .)) .Values.pvc.name }}
  labels:
    {{- include "workload.commonLabels" . | nindent 4 }}
  {{- with .Values.pvc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml (default (list "ReadWriteOnce") .Values.pvc.accessModes) | nindent 4 }}
  resources:
    requests:
      storage: {{ required "pvc.resources.requests.storage is required" .Values.pvc.resources.requests.storage }}
  {{- with .Values.pvc.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  {{- with .Values.pvc.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.pvc.volumeMode }}
  volumeMode: {{ . }}
  {{- end }}
{{- end }}
