{{- if and (include "chart.isStatefulSet" . | eq "true") .Values.service.headlessEnabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.headlessName" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    {{- include "chart.annotations" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
