{{- /*
templates/workload.yaml
- Render Deployment | StatefulSet tùy .Values.workload.kind
- Selector dùng bộ nhãn khuyến nghị (app.kubernetes.io/name + instance)
- Pod Template dán commonLabels + podLabels; annotations từ values
- StatefulSet: spec.serviceName dùng headless nếu bật, ngược lại dùng service thường
*/ -}}

{{- $kind := (default "Deployment" .Values.workload.kind) -}}

apiVersion: apps/v1
kind: {{ $kind }}
metadata:
  name: {{ include "workload.fullname" . }}
  labels:
{{ include "workload.commonLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.workload.replicas }}
  revisionHistoryLimit: {{ .Values.workload.revisionHistoryLimit }}
  {{- if eq $kind "Deployment" }}
  strategy:
{{ toYaml .Values.workload.strategy | nindent 4 }}
  {{- else if eq $kind "StatefulSet" }}
  serviceName: {{ if .Values.service.headlessEnabled }}{{ include "workload.headlessName" . }}{{ else }}{{ include "workload.serviceName" . }}{{ end }}
  updateStrategy:
{{ toYaml .Values.workload.statefulSetUpdateStrategy | nindent 4 }}
  {{- end }}

  selector:
    matchLabels:
{{ include "workload.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
{{ include "workload.commonLabels" . | nindent 8 }}
      {{- with .Values.workload.podLabels }}
{{ toYaml . | nindent 8 }}
      {{- end }}
      annotations:
{{ include "workload.commonAnnotations" . | nindent 8 }}
      {{- with .Values.workload.podAnnotations }}
{{ toYaml . | nindent 8 }}
      {{- end }}

    spec:
      serviceAccountName: {{ include "workload.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.workload.automountServiceAccountToken }}

      terminationGracePeriodSeconds: {{ .Values.workload.terminationGracePeriodSeconds }}
      securityContext:
{{ toYaml .Values.workload.podSecurityContext | nindent 8 }}

      {{- with .Values.workload.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}

      {{- with .Values.workload.dnsConfig }}
      dnsConfig:
{{ toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.workload.hostAliases }}
      hostAliases:
{{ toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.workload.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.workload.tolerations }}
      tolerations:
{{ toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.workload.affinity }}
      affinity:
{{ toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.workload.topologySpreadConstraints }}
      topologySpreadConstraints:
{{ toYaml . | nindent 8 }}
      {{- end }}

      imagePullSecrets:
{{ toYaml .Values.workload.imagePullSecrets | nindent 8 }}

      # ===== InitContainers =====
      {{- with .Values.workload.initContainers }}
      initContainers:
{{ toYaml . | nindent 8 }}
      {{- end }}

      # ===== Volumes =====
      volumes:
{{ toYaml .Values.workload.volumes | nindent 8 }}

      containers:
        # ===== Main container =====
        - name: {{ include "workload.chartLabel" . }}
          image: {{ include "workload.imageRef" . | quote }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.workload.specs.image.pullPolicy }}
          {{- with .Values.workload.specs.command }}
          command:
{{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.workload.specs.args }}
          args:
{{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.workload.specs.env }}
          env:
{{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.workload.specs.envFrom }}
          envFrom:
{{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.workload.specs.ports }}
          ports:
{{ toYaml . | nindent 12 }}
          {{- end }}
          resources:
{{ toYaml .Values.workload.specs.resources | nindent 12 }}
          {{- with .Values.workload.specs.volumeMounts }}
          volumeMounts:
{{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.workload.specs.livenessProbe }}
          livenessProbe:
{{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.workload.specs.readinessProbe }}
          readinessProbe:
{{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.workload.specs.startupProbe }}
          startupProbe:
{{ toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
{{ toYaml .Values.workload.specs.securityContext | nindent 12 }}

        # ===== Sidecars =====
        {{- with .Values.workload.sidecars }}
{{ toYaml . | nindent 8 }}
        {{- end }}
